name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", pypy3]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: make install-tests
      - run: make coverage

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
